@PersonRestAPI_HostAddress = https://localhost:7078

GET {{PersonRestAPI_HostAddress}}/persons
Accept: application/json

###
POST {{PersonRestAPI_HostAddress}}/persons
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "firstName": "Ola",
  "lastName": "Normann",
  "age": 30
}
###
DELETE {{PersonRestAPI_HostAddress}}/persons/1

###
PUT {{PersonRestAPI_HostAddress}}/persons/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "firstName": "Ola",
  "lastName": "Normann",
  "age": 40
}
